export const SYSTEM_PROMPTS = `PLACEHOLDER_SYSTEM_PROMPT`;

export const SAMPLE_PROMPTS = [
    "PLACEHOLDER_SAMPLE_PROMPT_1",
    "PLACEHOLDER_SAMPLE_PROMPT_2",
    "PLACEHOLDER_SAMPLE_PROMPT_3",
];
